### ISSUE TITLE
Source attribution of single ST

### ISSUE THREAD

**Issue by nbawe** [jmarshallnz/islandR#20]
Is it possible using source attribution within single ST? - Can I use for example cgMLST alleles with artificially created STs from cgMLST profiles?

If yes should I use only varianle loci present all or all loci and mark missing as 0?

Thanks

**Comment by jmarshallnz** [comment]
Yes, you can do attribution using cgMLST profiles within a single ST.

Using 0 for missing will work, and using only variable genes makes sense. You can generate an ST column by concatenation of the gene columns.

We’ve successfully used this method with NZ data.

Note you should use the fix_likHi6 branch for this as it addresses a problem that can arise with many genes, which hasn’t yet been merged into master.

Let me know how you get on 😀

**Comment by nbawe** [comment]
Could you help me with the R-script. How I could run it without the location info? I would just want to know the distribution for the whole set.

ADDITIONALLY

Can I use `dat$Location = 0`?

Could you also help how to get 95%CI valuea from violin plot?


Thanks

**Comment by nbawe** [comment]
Can I use `dat$Location = 0`?

**Comment by jmarshallnz** [comment]
Just use Source ~ 1 as the formula in attribution

**Comment by nbawe** [comment]
Just to be clear:

Do I still need to run this:
`# Fit the attribution model for human cases, estimating separately by location (urban/rural)
dat = subset(manawatu, Source == "Human")
dat$Location = factor(ifelse(dat$UR2006_num <= 0, "Rural", "Urban"))`

Or just:
`mod = attribution(Source ~ 1, st, data=dat)`

If the first is not used what is `data` in `attribution`

Could you also help how to get 95%CI valuea from violin plot?


I apologize for so many questions and appreciate your help.

**Comment by nbawe** [comment]
Previous got me an error:

`Error in attribution(Source ~ 1, st, data = dat) : 
  Have types that aren't found in the sampling distribution of the sources
`

Did you mean `ST ~ 1` ?
