### ISSUE TITLE
Extract posterior probability for each ST

### ISSUE THREAD

**Issue by domenico-simone** [jmarshallnz/islandR#22]
Hi,

I am wondering if there's any straightforward way to extract the PPs ST-wise, in order to get a plot like Figure 3 in the paper https://royalsocietypublishing.org/doi/10.1098/rsif.2018.0534#d3e3096

Thank you!

Domenico

**Comment by jmarshallnz** [comment]
Sure, the code for all the figures in the paper are in the paper github:

https://github.com/jmarshallnz/dirichlet_island/blob/master/fig_genotype_dist.R

I suspect this is easier now than that code, as there is a as.data.frame.sample_dist:

https://github.com/jmarshallnz/islandR/commit/4ac5dd9c93947a493babed4f94eb8b6b0f3ced32

So I suspect that the code at line 16 can just be done by using `as.data.frame(st_i)`? https://github.com/jmarshallnz/dirichlet_island/blob/master/fig_genotype_dist.R#L16
Jonathan

**Comment by jmarshallnz** [comment]
Yes, this will work to extract to a tidy data frame ready for plotting. Note that it outputs log(p) rather than p:

```r
library(islandR)

# Fit the sequence type distribution using the island model
num_samples <- 10

st_i = st_fit(formula = Source ~ ST,
              non_primary = "Human",
              data = manawatu,
              method = "island",
              sequences = ~ ASP + GLN + GLT + GLY + PGM + TKT + UNC,
              samples=num_samples)

test <- as.data.frame(st_i, types = c(403, 2343, 2026, 474))
```

The `types` parameter defaults to `NULL` which will return the sampling distribution for all types.

**Comment by domenico-simone** [comment]
Hi @jmarshallnz thank you, that worked like a charm! So, if I understood correctly, I can use the info provided by the resulting figure to "break down" the source attribution results by ST, or at least to make this kind of hypothesis: "If I find a campylobacteriosis patient with ST-2343, there are high chances that the source of the infection was poultry, based on the AIM; if the ST is 403, high chances are the source of infection is ruminants". Am I right?

Thank you for your prompt reply and support!

**Comment by jmarshallnz** [comment]
Not quite, but close. The results in the `sample_dist` object from `st_fit()` are roughly $\log(P(ST \mid source))$, so if you exponentiate you'd get $P(ST \mid source)$. What you are after is $P(source \mid ST)$. Ofcourse, you can reverse these by a standard application of Bayes' Theorem if you have priors $P(source)$.

For the figure, we assume apriori that $P(source)$ is equal for all sources, whereby you just get $P(source \mid ST) = \frac{P(ST \mid source)}{\sum_j P(ST \mid j)}$. This is what the `mutate(P = P/sum(P))` line is doing when producing `final` in the code I linked above.

Ofcourse, each source is almost certainly not apriori likely if the ST you have is coming from a human - but it will nonetheless give you some idea :)

You can also get posterior probabilities for $P(source | ST)$ (conditional on your observed human data) by first estimating $P(source)$ using `attribution()`, and then putting that through Bayes' Theorem.

**Comment by domenico-simone** [comment]
@jmarshallnz thank you for the explanation! I'll give it a try. Any chance you will implement this directly through the package? 

Thank you,

Domenico

**Comment by jmarshallnz** [comment]
I guess we could probably have some sort of `compute_posterior` function where you pass it P(source) and it does Bayes' for the user.

It's very unlikely I'll have time to look at it in the short term though! But if you come up with something for this I'm happy to look at it for inclusion :)
