### ISSUE TITLE
Branch to use for using cgMLST data

### ISSUE THREAD

**Issue by domenico-simone** [jmarshallnz/islandR#23]
Hello,

I am interested in using islandR with cgMLST data. In #20 it's recommended to use a specific branch (fix_likHi6) but I can't see it in the available branches. Has it been merged in the master branch? Would you suggest any other best practice to use islandR with cgMLST data (or any other typing schema with a lot of markers)?

Thank you

Domenico

**Comment by jmarshallnz** [comment]
Yes, can confirm it is merged into main.

Generally if using cgMLST or similar, one thing to look for is whether the recombination or mutation rates are estimated via a pooled analysis or per-source. What can happen with lots of genes is that any differences in the estimates of these between source are amplified dramatically (essentially to the power of the number of genes) which can mean that P(source | ST) can be dramatically different.

You can switch to a pooled analysis by specifying `control = list(mutation = "constant", recombination = "constant")` in `st_fit`.

**Comment by domenico-simone** [comment]
Thank you @jmarshallnz! I'll give it a try and report a feedback.
